### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by rockdaboot** [vanrein/quick-der#2]
Looks like something is missing:

$ make
...
make[1]: Entering directory '/usr/oms/src/quick-der/rfc'
PYTHONPATH='../tool/asn1ate' ../tool/asn1ate/asn1ate/asn2quickder.py rfc3280.asn1
/bin/sh: 1: ../tool/asn1ate/asn1ate/asn2quickder.py: not found
Makefile:26: recipe for target 'rfc3280.h' failed
make[1]: *** [rfc3280.h] Error 127
make[1]: Leaving directory '/usr/oms/src/quick-der/rfc'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vanrein** [comment]
Hi Tim,

> Looks like something is missing:

Yes, looks like it.  Never used this in git before

1. did you add the git submodules?
2. can you send me your .gitmodules to check?
3. what do you find in the directory tool/asn1ate/asn1ate/*.py ?

-Rick

**Comment by vanrein** [comment]
Ah,

The .gitmodules was off, I remember doing it by hand in an "obviously correct" manner.  But quoting the wrong project URL :-S  Place update and redo the git submodules thingy.  Sorry.

BTW... when you're already mapping RFC 3280 (PKIX) to a .h file then you've already done the work.

Oh... and if you add stuff for ISDN then you are more than welcome to use this project to backup the modules that you can pass through Quick-DER too!  I had to modify small bits (without interfering with the data matched) as documented in rfc/*.asn1 -- if you need help with that just let me know --> provided that you are going to share back.

-Rick

**Comment by vanrein** [comment]
Tim,

I had a few more things to learn about submodules, namely to --rebase
them.  I did that now, and checked in the result.  Pulled it and built,
both with and without "git submodule update --init" to load the submodulues.

The submodules are there to convert rfc/*.asn1 files into rfc/*.h files
that will be made available for #include <quick-der/rfc4120.h> and
such.  I already mapped LDAP, Kerberos5, and two iterations of the PKIX.

I added a subdirectory "itu" just like "rfc" and welcome you to put
stuff in it like "itu-q921.asn1" and have it mapped automatically to .h
files to install for #include <quick-der/itu-q21.h> -- the intention of
Quick DER is to make it quick and easy to load ASN.1 / DER parsers.


Cheers,
 -Rick

**Comment by rockdaboot** [comment]
Rick,

I won't have the time to go into ASN.1 details in the near future.

I now pulled in  your changes and the submodules. Just a few things:
 - you should remove the INSTALL file (it's FSF copyrighted and seems to be a remnant of autotools)
 - you should have a description of how to build incl. all dependencies (e.g. I had to pull in package 'python-pyparsing')
 - It would be a good idea to have a 'bootstrap' or 'autogen' script which does a few checks/things (e.g. pulling in git submodules). [This](https://github.com/rockdaboot/libpsl/blob/master/autogen.sh) is what I use for libpsl - feel free to amend it for your needs.
 - You hardcoded 'gcc', maybe you can use $CC (and if not defined set it to gcc).

Right now I get
```
make[1]: Entering directory '/usr/oms/src/quick-der/rfc'
In file included from rfc3280.c:1:0:
rfc3280.h:11:27: fatal error: quick-der/api.h: No such file or directory
compilation terminated.
```

Building should be possible without prior installing.

**Comment by vanrein** [comment]
Hi Tim,

Good remarks.  I'll try to remember them; adding them as issues is more likely to be a constant reminder though...

Thanks,
 -Rick

**Comment by vanrein** [comment]
* The INSTALL isn't there (anymore) the only thing here is INSTALL.MD; it outlines `./configure` which will run, though it is trivial.
 * Dependencies for asn1ate are documented with asn1ate itself
 * I do not share the belief that `bootstrap` or `autogen` makes life any better -- too pragmatic and far too little conceptual overview in these tools to actually build something reliable
 * It sounds nice to have a `$CC` variable, but it only really makes sense if all `$CFLAGS` and such are accordingly parameterised -- which people are not doing and they're just getting away with it through commandline compatibility, which is most likely to be triggered by using the `gcc` name as well.

I'm not saying these points will not be re-addressed in the future, but they don't seem to fit the project for the time being.
