### ISSUE TITLE
What we can der_unpack() we should also der_pack()

### ISSUE THREAD

**Issue by vanrein** [vanrein/quick-der#33]
The Python code does clever things with substitute classes and native types.  This is wonderful to work with, but we should also make it work when repacking into DER.

The Python code introduces `None` for non-existent entries; it even sets all fields to `None` when creating an empty instance of an ASN.1 type-named class.  When the entries that are `None` conform to syntax, these should translate into proper DER-packed output.

**Comment by adriaandegroot** [comment]
e315e96 adds some tests that check the idempotency of unpack(pack()) (so starting from python values). I don't think that's quite what you're getting at with this issue, but ..

**Comment by vanrein** [comment]
This is useful in its own right, thanks.

I am indeed looking for the other way around, so `pack(unpack())`, because it will allow us to pickup life samples from protocols and files anywhere.  It is also a format that users of Quick DER could use to check a buggy experience and supply us with it, and make it easy to check for the rest of the package's life.

It may be possible to generate (a lot of) examples by specifying a set of "nasty cases" per primitive type, and let the code work on similarly nasty constructions.

**Comment by vanrein** [comment]
This should be remedied with [version-1.1-alpha1](https://github.com/vanrein/quick-der/releases/tag/version-1.1-alpha1) and forward.
