### ISSUE TITLE
assumes python is in install prefix

### ISSUE THREAD

**Issue by gijzelaerr** [vanrein/quick-der#35]
at the moment it seems python code is installed in `<PREFIX>lib/python2.7/site-packages/`.

This probably works fine if you install in `/usr/local`, but fails in most other cases. 

Probably better to do is:
* Get current Python from path, which can be optionally overriden using cmake
* Ask Python where its `site-packages` folder is.

This works in most cases, also with virtualenvs. Alternatively you could just split the python code out and safe frustration, don't use cmake for Python and have a pipable python package.

**Comment by gijzelaerr** [comment]
this is actually not true, it looks like `python setup.py` is called to install the python modules.

I have to come back on my statement, this is actually not working properly when making a debian package. I install the code into a prefix which will become the Debian package, but the CMake logic calls python to install the python module in the python folder.

```
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-55374.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/
```

**Comment by adriaandegroot** [comment]
You might want to look at setting *DESTDIR*, e.g. `DESTDIR=/tmp/temproot make install` will install under `<DESTDIR><PREFIX>`. Unfortunately that also means adding `<DESTDIR><PREFIX>` to *PYTHONPATH*, since setuptools are picky.

If you're getting particular build / install errors, try running `make VERBOSE=1` (optionally with whatever target you need) to see exactly what's happening.

**Comment by gijzelaerr** [comment]
My experience is that if you automatically call one build system from the other you may run into problems. My packaging problem would be solved if I could call cmake to install the shared library and call a setup.py script to install the python code.

**Comment by gijzelaerr** [comment]
To elaborate, i'm making a Debian package out of quick-der. I'm almost there, only the python module is installed in the wrong location. Debian comes with all kind of smart tools, that automatically configure cmake projects and python project in such a way that the installation is done in a prefix which is the base of a package. The problem now is that Debian configures cmake to install in a prefix, but somehow this prefix is not propagated to the python installation, which will result in an installation attempt in /usr/local.

**Comment by adriaandegroot** [comment]
We could easily add a CMake knob NO_INSTALL_PYTHON, which does do the building and/or futzing around with the Python modules, while skipping the cmake-generated call to `setup.py install`. That would leave the way open for you to cd into the build-dir and run `setup.py` there yourself, with appropriate flags.

At least one problem with the existing CMake calls in install is that they **don't** respect DESTDIR.

**Comment by adriaandegroot** [comment]
Also FWIW, you may want to look at packaging arpa2/arpa2cm, which is a collection of CMake modules for the whole ARPA2 stack. We started on that in an effort to create one set of (high quality) CMake modules for "our kind of work". These will take over most of the CMake modules from individual parts of the stack (e.g. Quick DER will lose all but MactroASN1Module.cmake)
