### ISSUE TITLE
cmake files installed in wrong location

### ISSUE THREAD

**Issue by gijzelaerr** [vanrein/quick-der#37]
they are installed in `<PREFIX>/lib/cmake/Quick-DER` but I'm quite sure that should be `<PREFIX>/share/cmake/Modules`

**Comment by adriaandegroot** [comment]
No. `<PREFIX>share/cmake/Modules` is where CMake itself installs its own modules; this is part of the standard CMake search path, but not where you necessarily install stuff yourself. On arch-based systems, this may be `<PREFIX>share/cmake-<VERSION>/Modules`. CMake itself searches in a [bunch of places](https://cmake.org/cmake/help/v3.9/command/find_package.html).

KDE, Qt, xapian, libxml2, yaml-cpp and clang all install their CMake files to `<PREFIX>lib/cmake/`on the systems I've looked at.

**Comment by gijzelaerr** [comment]
hm, interesting. On a random debian system I get this:
```
$ dpkg -S .cmake | grep -v cmake-data | sort
libarmadillo-dev: /usr/share/doc/libarmadillo-dev/examples/Makefile.cmake
libeigen3-dev: /usr/lib/cmake/eigen3/Eigen3Config.cmake
libeigen3-dev: /usr/lib/cmake/eigen3/UseEigen3.cmake
libpurify-dev: /usr/share/cmake/purify/PurifyConfig.cmake
libpurify-dev: /usr/share/cmake/purify/PurifyConfigVersion.cmake
libpurify-dev: /usr/share/cmake/purify/PurifyTargets.cmake
libpurify-dev: /usr/share/cmake/purify/PurifyTargets-none.cmake
libsopt-dev: /usr/share/cmake/sopt/SoptConfig.cmake
libsopt-dev: /usr/share/cmake/sopt/SoptConfigVersion.cmake
libsopt-dev: /usr/share/cmake/sopt/SoptCPPTargets.cmake
libsopt-dev: /usr/share/cmake/sopt/SoptCPPTargets-none.cmake
libspdlog-dev: /usr/lib/cmake/spdlog/spdlogConfig.cmake
libspdlog-dev: /usr/lib/cmake/spdlog/spdlogConfigVersion.cmake
libspdlog-dev: /usr/lib/cmake/spdlog/spdlogTargets.cmake
```

As often with CMake, there doesn't seem to be one right way to do this.
