### ISSUE TITLE
'NoneType' object has no attribute 'symbols_imported' using latest asn1ate

### ISSUE THREAD

**Issue by gijzelaerr** [vanrein/quick-der#43]
I've modified the python code to directly use asn1ate from github, see the pygijs branch:

https://github.com/vanrein/quick-der/tree/pygijs

When I run `asn2quickder` with the latest `asn1nate` i run into troubles:
```
/Users/gijs/Work/quick-der/python/.virtualenv/bin/python /Users/gijs/Work/quick-der/python/scripts/asn2quickder ../../doc-pkcs11/doc/RemotePKCS11.asn1
Traceback (most recent call last):
  File "/Users/gijs/Work/quick-der/python/scripts/asn2quickder", line 1580, in <module>
    for rm in dm.imports.symbols_imported.keys():
AttributeError: 'NoneType' object has no attribute 'symbols_imported'

Process finished with exit code 1
```

**Comment by vanrein** [comment]
You tried this on a module without IMPORTS, and I bet that's the cause:

This sounds like a difference between our IMPORTS code and kimgr's... he didn't clone our work but wrote it from scratch, as far as I can tell.

Could you prefix the loop with "if dm.imports is None: continue" or the opposite with indentation and such please?

**Comment by adriaandegroot** [comment]
Confirmed in master on FreeBSD as well.

The module without imports is rfc5805

**Comment by gijzelaerr** [comment]
fixed per https://github.com/vanrein/quick-der/commit/43aa528c608632bf4088eda0023160963a6ebb98
