### ISSUE TITLE
Enable travis-ci

### ISSUE THREAD

**Issue by gijzelaerr** [vanrein/quick-der#46]
travis-ci is a continues integration service that runs a custom script for every commit or PR. You can for example compile the code and run a test suite. You can even configure it to upload code to for example pypi on a release. It is very useful and free for open source software. It also integrates very nicely with github.

an example:

https://github.com/gijzelaerr/pymonetdb
https://travis-ci.org/gijzelaerr/pymonetdb

**Comment by gijzelaerr** [comment]
@vanrein I can't enable travis since I dont own this repo.

**Comment by vanrein** [comment]
Hoi,

> @vanrein <https://github.com/vanrein> I can't enable travis since I
> dont own this repo.

Alweer een goed idee.  Ik heb travis ge-enabled met een (net gemaakte) account vanrein op travis-ci.org

Wil jij een .yml file toevoegen?  Zover ik zien kan is dat alles, maar als ik nog iets moet doen hoor ik het vast wel :)

_Rick

**Comment by adriaandegroot** [comment]
You might also want to create an arpa2 account on Travis, for the projects that come from there (e.g. LillyDAP).

On a related integration-note, it'd be nice to have GH notifications (of PRs, pushes) sent to IRC as well. I've tested them once on this repo, they work even with the arpa2 irc server.

**Comment by gijzelaerr** [comment]
travis is enabled now.
