### ISSUE TITLE
use semantic versioning

### ISSUE THREAD

**Issue by gijzelaerr** [vanrein/quick-der#55]
Makes it easier to create a package

https://semver.org/

**Comment by adriaandegroot** [comment]
What does this issue mean? Current quick-der released version 1.2.3; it has a possibly unfortunate git tag name of version-1.2-3, and the CMake tooling generates a version number based on git-explain, like 1.2.3-41-gaed786d for current master.

**Comment by gijzelaerr** [comment]
ah! why do the git tags differ from the version numbers? 

I extract the version number from the git tag when building the Debian packages using uscan.

**Comment by vanrein** [comment]
Adriaan promised to make a pass over ARPA2 projects to relieve us of our/my initial versioning madness.
