### ISSUE TITLE
der_unpack() can use const for input cursor

### ISSUE THREAD

**Issue by vanrein** [vanrein/quick-der#56]
We can use `der_unpack(const dercursor *crs, ...)`

When this is done, the calls from [keehive](https://github.com/arpa2/keehive) can also be made with `static const` structures.

**Comment by vanrein** [comment]
Resolved in 0fe73c3853130a1885b0131b1ce4a95d45fd1d48

**Comment by adriaandegroot** [comment]
The assumption that `*crs` could be const was false, since the function is documented to return the (changed) end position in `*crs`. This change broke tests and falsified the documentation for the function.

**Comment by vanrein** [comment]
Adriaan is right, I was too quick in thinking that it made sense to make crs a const.  This has now been reverted in the `master` and `keehub` branches.  Gijs, a copy into a local dercursor will probably get you where you want.

I suspect `dercursor *const crs` is what we should consider, but this gets more into C++ than I feel comfortable with, so until someone figures that out, it's reversed.
