### ISSUE TITLE
Consider return-type consistency of der_pack()

### ISSUE THREAD

**Issue by vanrein** [vanrein/quick-der#58]
Apparently, `der_pack()` is the only function that does not return a success/failure value and sets `errno` accordingly.  Instead, `der_pack()` returns a byte size.  Consider better alignment.

The size output could be a `size_t *` output parameter.  It may be set to 0 to indicate "please figure it out" and may then be validated upon 2nd call.  The output may in both cases be an error code.  (The error code could be retained with output parameter initialisation to a weird value (like 0 or 1) to indicate keeping `errno` across calls.  This might simplify error handling &mdash; but at the expense of simplicity, so probably not a good idea).

It would seem to be possible to create a `#define der_pack()` with a parameter less, and map it to the function.  That would effectively allow for backward compatibility and a deprecation path.

**Comment by adriaandegroot** [comment]
You could bump the version of QD to, say, 2.0.0 with this change, and bump the .so version, which would make it clear to whatever clients QD has what is going on.

It doesn't look like `der_pack()` does anything with the error returns from (internal) `der_pack_rec()` so that would need to be fixed first.

**Comment by vanrein** [comment]
Actually, `der_iterate_first()` and `der_iterate_next()` also have special return values, to fit into nice usage patterns with `if` and `while`.

In general, a `bool` return value stating positively that something succeeded may be a nicer style in any case.

**Comment by vanrein** [comment]
With the same names, consistency would break a lot.  It's pretty bad already that I debugged `der_focus()`, `der_iterate_first()` and `der_iterate_next()` to allow for sane and intended/documented use of these functions -- work-arounds will probably suffer.
