### ISSUE TITLE
Dependency sort assignments in a module by default

### ISSUE THREAD

**Issue by gijzelaerr** [vanrein/quick-der#63]
Currently, this is done at various locations while I see no reason to not sort them by default after parsing the semantic model.

https://github.com/vanrein/quick-der/search?utf8=%E2%9C%93&q=dependency_sort&type=

**Comment by vanrein** [comment]
Would have been another way of doing it.  Frankly, the risk of code breaking is higher than the benefits of keeping it as is.  This is a one-shot program, so optimisations are not a concern, it's only about consistent behaviour.
