### ISSUE TITLE
How to write an ASN1 stream

### ISSUE THREAD

**Issue by WillianBR** [vanrein/quick-der#78]
### How to write an ASN1 stream

I'm looking for a small library to write an ANS1 stream.  I'm intended to use it into a embed system.
The basic idea is to enable the embed device to collect the data and write it to a stream (file or socket connection) as a ASN1 data flow.
Let's it got a pair of GPS coordenates and the device ID.  So it'll write something like (The colon only to simplicity display):

```
TYP:GPS
ID:ZYB9791
LAT:-15.7842556
LON:-47.9133991

```
1) [OCTET STRING] So the receiver could check the "TYP" to be aware of the record type.
2) [OCTET STRING]  Get the "ID" to identify the sender.
3) [SET OF INTEGER] Read the "LAT" and "LON" data (as INTEGER format) and use the data.

**_The main goal is to stream structured random data with the minimum bandwidth comsuption or disk._**

#### Does anyone has a hint?

**Comment by vanrein** [comment]
This tool should be a perfect fit.  But it has moved here, so I am closing the discussion on GitHub.  Please feel free to start a new issue on the new platform if you like.  But the direct answer to your question is that this tool is what you need: very small, very efficient and rather straightforward to use.  You can use the ASN.1 compiler to produce structure files for you.

New location: https://gitlab.com/arpa2/quick-der

**Comment by WillianBR** [comment]
@vanrein  Thank you! I'll follow the gitlab repo and start a few tests!
